services:
  sd-webui-forge:
    build: .
    ports:
      - "6006:6006"
    environment:
      - COMMANDLINE_ARGS=--port 6006 --listen --precision full --no-half --share --api --cuda-stream --cuda-malloc
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              count: "all"
              capabilities: ["gpu"]
